FROM nginx:latest
LABEL maintainer 'Arthur Pereira Machado <arthur at arthurpereiramachado01@gmail.com>'

RUN echo '<h1>Sem Conteudo</h1>' > /usr/share/nginx/html/conteudo.html
COPY *.html /usr/share/nginx/html