version: '3'
volumes: 
    dados:
services: 
    db:
        image: postgres:9.6
        restart: always
        environment: 
            POSTGRES_PASSWORD: password
        volumes:
            # Volume dos dados
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    frontend:
        image: nginx:1.13
        volumes:
            # Site
            - ./web:/usr/share/nginx/html/
        ports: 
            - 80:80